server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # FRONTEND
    location / {
        proxy_pass http://frontend:5173;
    }

    # BACKEND API
    location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass backend:9000;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
}